name: Deploy realworld-app to GKE

on:
  push:
    paths:
      - 'react_redux_app_deploy/**'
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-central1-a
  GKE_CLUSTER: gke-ycit-tformers-default-dev
  IMAGE: react-redux
  DEPLOYMENT_NAME: react-redux-chart    

# Environment variables available to all jobs and steps in this workflow

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        gcloud auth configure-docker
    
    # Build the Docker image, for the real world app react-redux
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry, for the real world app react-redux
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
    
    # Install helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        
    # Deploy to the GKE cluster. Use Gcloud to get credentials and update or install the reactReduxChart into the cluster
    # Make sure to set the image.tag to be used in the reactReduxChart.values.yaml to the latest one. For the react-redux app deployment to use.
    - name: Deploy
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $PROJECT_ID
        helm upgrade --install $DEPLOYMENT_NAME-realworldapp $DEPLOYMENT_NAME \
          --set=image.tag=$GITHUB_SHA
        kubectl rollout status deployment/$DEPLOYMENT_NAME-realworldapp
        kubectl get services -o wide